name: "Build kernels"

on:
  workflow_dispatch: # This is what creates the "Run workflow" button

env:
  CONFIGURATION: "repos.json"
  OUT_DIR: "out"

jobs:
  Build-Kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: [ { "kernelSource": { "name": "A137F", "repo": "https://github.com/Tamzid228/my-kernel-source", "branch": "main", "device": "vendor/a13ve" } } ]
    steps:
       - name: "😄 Checkout"
         uses: actions/checkout@v4

       - name: "⭐ Install prerequisites"
         run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libncurses-dev libfl-dev

       - name: "⭐ Get kernel source"
         run: |
          git clone --depth=1 -b ${{ matrix.repos.kernelSource.branch }} ${{ matrix.repos.kernelSource.repo }} ${{ matrix.repos.kernelSource.name }}
          cd ./${{ matrix.repos.kernelSource.name }}
          # Fix common Clang unknown argument errors
          find . -type f -name "Makefile*" -exec sed -i 's/-mno-global-merge//g' {} +
          find . -type f -name "Makefile*" -exec sed -i 's/-fno-var-tracking-assignments//g' {} +

       - name: "⭐ Get toolchain"
         run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang
          # This line gives the compiler permission to run
          chmod -R +x ./clang/bin

       - name: "🔨 Build"
         run: |
          # Get the full path of the clang folder
          CLANG_PATH=$(pwd)/clang/bin
          cd ./${{ matrix.repos.kernelSource.name }}
          
          # Run Defconfig
          make O=../${{ env.OUT_DIR }} ARCH=arm64 \
          CC=${CLANG_PATH}/clang \
          CROSS_COMPILE=${CLANG_PATH}/aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=${CLANG_PATH}/arm-linux-gnueabi- \
          ${{ matrix.repos.kernelSource.device }}_defconfig
          
          # Start Compiling
          make O=../${{ env.OUT_DIR }} ARCH=arm64 \
          CC=${CLANG_PATH}/clang \
          CROSS_COMPILE=${CLANG_PATH}/aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=${CLANG_PATH}/arm-linux-gnueabi- \
          -j$(nproc --all)

       - name: "💛 Upload Image"
         uses: actions/upload-artifact@v4
         with:
          name: Image-Samsung-A13
          path: ./out/arch/arm64/boot/Image

       - name: "💙 Upload Image.gz"
         uses: actions/upload-artifact@v4
         with:
          name: Image.gz(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
          path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image.gz
          if-no-files-found: ignore
          retention-days: 7

       - name: "💜 Upload dtb"
         uses: actions/upload-artifact@v4
         with:
          name: dtb(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
          path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dtb
          if-no-files-found: ignore
          retention-days: 7

       - name: "❤️ Upload dtbo.img"
         uses: actions/upload-artifact@v4
         with:
          name: dtbo.img(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
          path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dtbo.img
          if-no-files-found: ignore
          retention-days: 7
